/* COUNT FOR DATA IMPORTED */
SELECT COUNT(*) FROM exercise_02.vehicle_collision;

/* LIMIT COUNT TO 100 */
SELECT * FROM exercise_02.vehicle_collision limit 100;

/* COUNT OF MOST PERSON_KILLED WITH BOROUGH AND DATE */
SELECT DISTINCT(BOROUGH), CRASH_DATE , COUNT(*) as COUNT FROM exercise_02.vehicle_collision GROUP BY NUMBER_OF_PERSONS_KILLED, CRASH_DATE order by count desc;

/* VEHICLE WITH MOST PERSON_KILLED */ 
SELECT DISTINCT(VEHICLE_TYPE_CODE_1) AS VEHICLE_TYPE
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_1 IS NOT NULL or VEHICLE_TYPE_CODE_1 <> ''
    UNION ALL
    SELECT distinct(VEHICLE_TYPE_CODE_2) AS VEHICLE_TYPE
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_2 IS NOT NULL or VEHICLE_TYPE_CODE_2 <> ''
    UNION ALL
    SELECT distinct(VEHICLE_TYPE_CODE_3) AS VEHICLE_TYPE
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_3 IS NOT NULL or VEHICLE_TYPE_CODE_3 <> ''
    UNION ALL
    SELECT distinct(VEHICLE_TYPE_CODE_4) AS VEHICLE_TYPE
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_4 IS NOT NULL or VEHICLE_TYPE_CODE_4 <> ''
    UNION ALL
    SELECT distinct(VEHICLE_TYPE_CODE_5) AS VEHICLE_TYPE
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_5 IS NOT NULL or VEHICLE_TYPE_CODE_5 <> '';
	
/* CRASHDATE */
SELECT CRASH_DATE
FROM exercise_02.vehicle_collision
WHERE SUBSTRING(CRASH_DATE, 7, 4) = 'CRASH_DATE';
SELECT YEAR(crash_date) AS crash_year
FROM exercise_02.vehicle_collision;
