SELECT 
  SUBSTRING(vc.CRASH_DATE, 7, 4) AS CrashYear,
  vc.BOROUGH AS Location,
  vt.VehicleType,
  COUNT(*) AS TotalIncidents,
  SUM(CAST(NULLIF(vc.NUMBER_OF_PERSONS_KILLED, '') AS UNSIGNED)) AS TotalKilled
FROM exercise_02.VEHICLE_COLLISION vc
JOIN (
  SELECT ID, VEHICLE_TYPE_CODE_1 AS VehicleType FROM exercise_02.VEHICLE_COLLISION
  UNION ALL
  SELECT ID, VEHICLE_TYPE_CODE_2 FROM exercise_02.VEHICLE_COLLISION
  UNION ALL
  SELECT ID, VEHICLE_TYPE_CODE_3 FROM exercise_02.VEHICLE_COLLISION
  UNION ALL
  SELECT ID, VEHICLE_TYPE_CODE_4 FROM exercise_02.VEHICLE_COLLISION
  UNION ALL
  SELECT ID, VEHICLE_TYPE_CODE_5 FROM exercise_02.VEHICLE_COLLISION
) vt ON vc.ID = vt.ID
WHERE vc.BOROUGH IS NOT NULL
  AND vc.BOROUGH <> ''
  AND vt.VehicleType IS NOT NULL
  AND vt.VehicleType <> ''
GROUP BY CrashYear, vc.BOROUGH, vt.VehicleType
ORDER BY TotalIncidents DESC
LIMIT 100;
