SELECT 
    SUBSTRING(CRASH_DATE, 7, 4) AS CRASH_YEAR,
    VEHICLE_TYPE,
    BOROUGH,
    COUNT(*) AS INCIDENT_COUNT
FROM (
    -- First vehicle type
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_1 AS VEHICLE_TYPE, BOROUGH
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_1 IS NOT NULL AND VEHICLE_TYPE_CODE_1 != ''

    UNION ALL

    -- Second vehicle type
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_2 AS VEHICLE_TYPE, BOROUGH
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_2 IS NOT NULL AND VEHICLE_TYPE_CODE_2 != ''

    UNION ALL

    -- Third vehicle type
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_3 AS VEHICLE_TYPE, BOROUGH
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_3 IS NOT NULL AND VEHICLE_TYPE_CODE_3 != ''

    UNION ALL

    -- Fourth vehicle type
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_4 AS VEHICLE_TYPE, BOROUGH
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_4 IS NOT NULL AND VEHICLE_TYPE_CODE_4 != ''

    UNION ALL

    -- Fifth vehicle type
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_5 AS VEHICLE_TYPE, BOROUGH
    FROM exercise_02.vehicle_collision
    WHERE VEHICLE_TYPE_CODE_5 IS NOT NULL AND VEHICLE_TYPE_CODE_5 != ''
) AS combined_vehicle_types
GROUP BY CRASH_YEAR, VEHICLE_TYPE, BOROUGH
ORDER BY INCIDENT_COUNT DESC, CRASH_YEAR DESC;
