CREATE TABLE IF NOT EXISTS `mydb`.`VEHICLE_COLLISION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Crash Date` VARCHAR(10) NULL,
  `Crash Time` VARCHAR(5) NULL,
  `Borough` VARCHAR(45) NULL,
  `ZIP_CODE` VARCHAR(8) NULL,
  `Latitude` VARCHAR(45) NULL,
  `Longitude` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `On_Street_Name` VARCHAR(45) NULL,
  `Cross_Street_Name` VARCHAR(45) NULL,
  `Off_Street_Name` VARCHAR(45) NULL,
  `Number_Of_Persons_Injured` VARCHAR(45) NULL,
  `Number_Of_Persons_Killed` VARCHAR(45) NULL,
  `Number_Of_Pedestrians_Injured` VARCHAR(45) NULL,
  `Number_Of_Pedestrians_Killed` VARCHAR(45) NULL,
  `Number_Of_Cyclist_Injured` VARCHAR(45) NULL,
  `Number_Of_Cyclist_Killed` VARCHAR(45) NULL,
  `Number_Of_Motorist_Injured` VARCHAR(45) NULL,
  `Number_Of_Motorist_Killed` VARCHAR(45) NULL,
  `Contributing_Factor_Vehicle_1` VARCHAR(45) NULL,
  `Contributing_Factor_Vehicle_2` VARCHAR(45) NULL,
  `Contributing_Factor_Vehicle_3` VARCHAR(45) NULL,
  `Contributing_Factor_Vehicle_4` VARCHAR(45) NULL,
  `Contributing_Factor_Vehicle_5` VARCHAR(45) NULL,
  `Collision_Id` VARCHAR(45) NULL,
  `Vehicle_Type_Code_1` VARCHAR(45) NULL,
  `Vehicle_Type_Code_2` VARCHAR(45) NULL,
  `Vehicle_Type_Code_3` VARCHAR(45) NULL,
  `Vehicle_Type_Code_4` VARCHAR(45) NULL,
  `Vehicle_Type_Code_5` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
