SELECT count(*) FROM mydb.vehicle_collision;
SELECT VEHICLE_TYPE_CODE_1, SUM(NUMBER_OF_PERSONS_KILLED) AS total_killed 
FROM vehicle_collision 
GROUP BY VEHICLE_TYPE_CODE_1 
ORDER BY total_killed DESC LIMIT 1;

SELECT CRASH_DATE, SUM(NUMBER_OF_PERSONS_KILLED) AS total_killed FROM vehicle_collision GROUP BY CRASH_DATE ORDER BY total_killed DESC LIMIT 1;

SELECT DISTINCT(BOROUGH), SUBSTRING(CRASH_DATE, 7, 4) YEAR , ZIP_CODE, COUNT(*) AS Total_Killed
FROM vehicle_collision
where CRASH_DATE IS NOT NULL
AND BOROUGH IS NOT NULL
GROUP BY BOROUGH
ORDER BY TOTAL_KILLED DESC, YEAR DESC, BOROUGH DESC;
