SELECT
    DISTINCT (VEHICLE_TYPE), SUBSTRING(CRASH_DATE, 7, 4) AS YearOfCrash,
    VEHICLE_TYPE,
    SUM(CASE WHEN NUMBER_OF_PERSONS_KILLED > 0 THEN NUMBER_OF_PERSONS_KILLED ELSE 0 END) AS TotalKilled
FROM (
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_1 AS VEHICLE_TYPE, NUMBER_OF_PERSONS_KILLED FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_2, NUMBER_OF_PERSONS_KILLED FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_3, NUMBER_OF_PERSONS_KILLED FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_4, NUMBER_OF_PERSONS_KILLED FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_5, NUMBER_OF_PERSONS_KILLED FROM `exercise_02`.`VEHICLE_COLLISION`
) AS Subquery
WHERE VEHICLE_TYPE IS NOT NULL AND VEHICLE_TYPE != ' ' AND NUMBER_OF_PERSONS_KILLED > 0
GROUP BY YearOfCrash, VEHICLE_TYPE
ORDER BY TotalKilled DESC, YearOfCrash, VEHICLE_TYPE;SELECT
    DISTINCT (VEHICLE_TYPE),
    SUBSTRING(CRASH_DATE, 7, 4) AS YearOfCrash,
    VEHICLE_TYPE,
    SUM(CASE WHEN NUMBER_OF_PERSONS_KILLED > 0 THEN NUMBER_OF_PERSONS_KILLED ELSE 0 END) AS TotalKilled,
    BOROUGH 
FROM (
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_1 AS VEHICLE_TYPE, NUMBER_OF_PERSONS_KILLED, BOROUGH FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_2, NUMBER_OF_PERSONS_KILLED, BOROUGH FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_3, NUMBER_OF_PERSONS_KILLED, BOROUGH FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_4, NUMBER_OF_PERSONS_KILLED, BOROUGH FROM `exercise_02`.`VEHICLE_COLLISION`
    UNION ALL
    SELECT CRASH_DATE, VEHICLE_TYPE_CODE_5, NUMBER_OF_PERSONS_KILLED, BOROUGH FROM `exercise_02`.`VEHICLE_COLLISION`
) AS Subquery
WHERE VEHICLE_TYPE IS NOT NULL AND VEHICLE_TYPE != ' ' AND NUMBER_OF_PERSONS_KILLED > 0
GROUP BY YearOfCrash, VEHICLE_TYPE, BOROUGH
ORDER BY TotalKilled DESC, YearOfCrash, VEHICLE_TYPE, BOROUGH;
